add support of bulk operations for ORM in ORACLE and SQLite backends
SOCI/soci pull request #1053
Opened 2023-05-29 11:25 UTC by vyskubov

Hello everyone,

I am excited to submit this pull request, which (re)introduces support for bulk operations in the SOCI library's ORM (Object-Relational Mapping) functionality. This work is based on the initial [groundwork](https://github.com/SOCI/soci/pull/168) laid by @abc100m, and I have built upon their contributions to enhance the capabilities of the library.

I would appreciate it if the community could review and provide feedback on the changes. Your insights and suggestions are valuable in ensuring the quality and effectiveness of this new feature.

Thank you for your attention and consideration. I look forward to collaborating with you all to further enhance the SOCI library.

Best regards,

2023-05-31 22:30 UTC, vadz reviewed
Thanks for the PR but I have a few questions just after the first very quick look at it:

1. Could you please try to minimize the number of unrelated changes? For examples, in several places `at(pos)` is replaced with `[pos]` which is not obviously right but even if it is, it would be much better to make it in a separate PR. There are also a lot of whitespace-only changes that really should be avoided.
2. Why are the new tests different for Oracle and SQLite? Is there some actual difference between the backends functionality and, if so, what is it? And if not, could we please have these tests in the common code?
3. And, of course, there are the the CI failures, could you please look at them?

I'll try to have a more detailed look at this later, but fixing (1) would be really helpful.

TIA!

2023-06-02 16:29 UTC, vadz commented
>     1. I have reverted all the whitespace-only changes.

Thanks!

> Regarding the replacement of `at(pos)` with `[pos]`, these changes were already present in the original PR, so I simply included them as-is.

Sorry for not realizing this.

> However, I have now reverted these changes for the time being. It's worth mentioning that the usage of `at(pos)` and `[pos]` in this file is inconsistent, which could be addressed in a separate PR.

I agree that inconsistencies should be fixed but it's definitely better to do them in a separate PR. Thanks for fixing this up too!

2023-08-22 06:33 UTC, asmwarrior commented
What is the status of this PR, I think the bulk adding is a very important feature for soci.

I have a similar discussion issue discussion here: [ORM: What is the correct way to bulk add a lot of rows? · Issue #1066 · SOCI/soci](https://github.com/SOCI/soci/issues/1066), in the issue, I have to use a for loop to add many rows, but I do need a simple way to do that.

Thanks.

2023-08-23 20:09 UTC, vyskubov commented
I apologize for abandoning this PR. I would like to complete the work on it; however, I currently have more urgent tasks to attend to.

Furthermore, I do not have a readily available development environment on Windows and FreeBSD. Any assistance would be greatly appreciated.

Thank you.

2024-01-02 19:26 UTC, vadz requested changes
Sorry, it doesn't seem like it can be merged in the current state, there are just too many unclear/unrelated things and commented out parts.

I also don't know if we really want to unconditionally replace scalar values with vectors, i.e. use vector of size 1 instead of simple values, it just looks like such a strange idea when we already have both scalar and vector versions.

Of course, maybe I just misunderstand things, but it's really hard to guess what is the intention/rationale here without any comments anywhere in sight.

2024-01-02 19:26 UTC, vadz commented on tests/sqlite3/test-sqlite3.cpp
> +        assert(vec_name.size() == 2);
All these `assert`s really need to be changed to `CHECK()`s.

2024-01-02 19:26 UTC, vadz commented on tests/sqlite3/test-sqlite3.cpp
> +    assert(vec_orm.size() == 2);
Here too.

2024-01-02 19:26 UTC, vadz commented on tests/sqlite3/test-sqlite3.cpp
> +         ++it)
Could use range-for loop here...

2024-01-02 19:26 UTC, vadz commented on include/soci/row.h
> +    row(std::size_t bulk_size = 1);
```suggestion
    explicit row(std::size_t bulk_size = 1);
```

2024-01-02 19:26 UTC, vadz commented on src/backends/sqlite3/vector-into-type.cpp
> +        std::shared_ptr<sqlite3_column> col1;
Why do we use a shared pointer here? It doesn't seem to be shared with anybody...

2024-01-02 19:26 UTC, vadz commented on src/backends/sqlite3/vector-into-type.cpp
> +        if (1 == endRow)
I wish there were a comment here explaining what is this test for. I can't understand what's going on here.

2024-01-02 19:26 UTC, vadz commented on include/soci/sqlite3/soci-sqlite3.h
> +
There doesn't seem to be any reason to extract this here, is there?

2024-01-02 19:26 UTC, vadz commented on include/soci/soci-platform.h
> +#define strncasecmp _strnicmp
This seems to be unused?

2024-01-02 19:26 UTC, vadz commented on include/soci/values.h
> +    std::map<std::string, std::size_t, CaseInsensitiveComparator> index_;
Why did this need to be changed to be case-insensitive?

2024-01-02 19:26 UTC, vadz commented on src/backends/oracle/statement.cpp
> +            type = dt_double;
This seems unrelated to the topic of this PR.

2024-01-02 19:26 UTC, vadz commented on src/backends/sqlite3/statement.cpp
> -
Removing this and inlining it looks a completely gratuitous change, was there really some reason for doing it?

2024-01-02 19:26 UTC, vadz commented on src/backends/sqlite3/statement.cpp
> +    return (1 == number) ? load_one() : load_rowset(number);
It looks like `hasVectorIntoElements_` is not used at all now and should be removed?

2024-01-02 19:26 UTC, vadz commented on include/soci/type-holder.h
> +// this class is for pass test [commontests.h, test12()],
This seems completely unrelated to the subject of this PR...

2024-11-17 19:09 UTC, vadz commented
It doesn't look like anything is going to happen here, so I have no choice but to close it, sorry.

2024-11-17 19:09 UTC, closed without merging